### ISSUE TITLE
Some tests are broken when converting cm2 to mm2

### ISSUE THREAD

**Issue by samuelrince** [Boavizta/boaviztapi#197]
## Bug description

Tests that compute impacts with a CPU component does not pass on the branch `fix/change-die-size-unit`.

## To Reproduce

Run the tests on the branch `fix/change-die-size-unit`.

## Expected behavior

All tests must pass, nothing else has changed but the units (cm2 to mm2)

**Comment by da-ekchajzer** [comment]
I just fix the cloud usage test in https://github.com/Boavizta/boaviztapi/commit/cad7a2a42a11778d527a8b24b1f9ff7fb49b3edd

The issue comes from the fact that in the tests files we use the "zen" nomenclature and in the data file we use the server nomenclature (Naples/Rome). This is a temporary fix, but I will work on another way to manage CPU family in the following days.

**Comment by da-ekchajzer** [comment]
And I fixed ```test_partial_server_2``` in c4ce1b4e3e633a457d9941c3c1f67bcef35296f9.

```die_size``` was changed to ```die_size_per_core``` in this specific test.
