### ISSUE TITLE
No use of Power Usage Effectiveness?

### ISSUE THREAD

**Issue by JacobValdemar** [Boavizta/boaviztapi#254]
I can't find PUE used anywhere in BoaviztAPI. Is that correct? And if yes, why is it not used?

**Comment by da-ekchajzer** [comment]
We do not use the power usage effectiveness because we only consider the impacts of the cloud instance and not its environment. If we include it, we also have to extend the scope to include the embedded impacts of the overhead (the same scope covered by the PUE) which is not possible for now since public data to qualify the environmental impacts of the datacenter environment are not available. 

If you are ok I am switching this issue to a discussion because we'll need to do it at some point.

In your opinion, should we : 

* Wait
* Wait and add a warning
* Add only the PUE and wait for the embedded impacts

**Comment by da-ekchajzer** [comment]
I will think about several ways to do it. @AirLoren any idea ?

**Comment by da-ekchajzer** [comment]
We should differentiate between : 

* The compute/storage overhead (redoundancy, control plan, internal services...)
* The IT Overhead (network)
* The non-IT (cooling, support, ...

I now remember that this issue is treated in this issue : https://github.com/Boavizta/boaviztapi/issues/71

We can continue the conversation in the other issue. I will close this one.
